
import React from 'react';

interface LegalModalProps {
  type: 'terms' | 'privacy';
  onClose: () => void;
}

export const LegalModal: React.FC<LegalModalProps> = ({ type, onClose }) => {
  const isTerms = type === 'terms';

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 md:p-8 animate-fade-in">
      <div className="absolute inset-0 bg-space-950/90 backdrop-blur-xl" onClick={onClose}></div>
      
      <div className="relative w-full max-w-3xl max-h-[80vh] bg-space-900 border border-white/10 rounded-3xl shadow-2xl flex flex-col overflow-hidden">
        <div className="p-6 border-b border-white/5 flex items-center justify-between bg-white/5">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 rounded-lg bg-gold-500/20 flex items-center justify-center text-gold-400 border border-gold-500/30">
              <i className={`fas ${isTerms ? 'fa-file-contract' : 'fa-user-shield'}`}></i>
            </div>
            <h3 className="text-xl font-display font-bold text-slate-100">
              {isTerms ? 'Terms of Service' : 'Privacy Policy'}
            </h3>
          </div>
          <button onClick={onClose} className="text-slate-500 hover:text-white transition-colors">
            <i className="fas fa-times text-xl"></i>
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6 md:p-10 space-y-8 text-slate-300 font-light leading-relaxed custom-scrollbar">
          {/* Harvey's Note */}
          <div className="bg-gold-500/5 border border-gold-500/20 p-6 rounded-2xl italic text-sm">
            <div className="flex items-center space-x-2 text-gold-400 mb-2 not-italic font-bold uppercase tracking-widest text-[10px]">
              <i className="fas fa-user-tie"></i>
              <span>Harvey's Note</span>
            </div>
            "Listen closely, my friend. In the world of medicine, precision and ethics go hand in hand. These documents ensure that our learning environment remains safe, professional, and transparent. Read them with the same care you'd give a difficult Doppler wave."
          </div>

          {isTerms ? (
            <div className="space-y-6">
              <section>
                <h4 className="text-gold-400 font-bold mb-2">1. Educational Nature</h4>
                <p>This application is strictly for educational and exam preparation purposes. It is designed to assist students in preparing for the ARDMS SPI exam. It does not provide medical certification, clinical advice, or diagnostic services.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">2. Not Medical Advice</h4>
                <p>The content generated by this app, including AI-driven explanations and simulations, should NEVER be used to diagnose or treat any medical condition. Always refer to official clinical guidelines and licensed professionals for medical practice.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">3. AI-Generated Content</h4>
                <p>Portions of this app utilize advanced AI (Google Gemini). While we strive for absolute accuracy, AI may occasionally generate incorrect scientific information. Users are encouraged to cross-reference with standard physics textbooks like Edelman or Kremkau.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">4. User Responsibility</h4>
                <p>You agree to use this tool as a supplement to, not a replacement for, formal sonography education. We are not liable for exam results or clinical performance.</p>
              </section>
            </div>
          ) : (
            <div className="space-y-6">
              <section>
                <h4 className="text-gold-400 font-bold mb-2">1. Data Sovereignty</h4>
                <p>We believe your progress is your own. All study data, quiz results, and profile information are stored exclusively in your browser's <strong>Local Storage</strong>. We do not maintain a central database of your personal study habits.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">2. AI Processing</h4>
                <p>When you interact with Harvey or generate custom mnemonics, your queries are processed by the Google Gemini API. These interactions are subject to Google's privacy protocols. We do not transmit your name or identifying information to the API.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">3. No Third-Party Tracking</h4>
                <p>This app does not use third-party advertising cookies or trackers. Your learning path remains private between you and your machine.</p>
              </section>
              <section>
                <h4 className="text-gold-400 font-bold mb-2">4. Audio Data</h4>
                <p>Any Text-to-Speech (TTS) processing occurs in real-time. We do not record or store the audio output or any voice inputs you may provide in interactive modes.</p>
              </section>
            </div>
          )}

          <div className="pt-10 pb-4 text-center">
            <p className="text-[10px] uppercase font-black text-slate-600 tracking-[0.3em]">Sonographic Survival Guide Compliance v4.2</p>
          </div>
        </div>

        <div className="p-6 bg-white/5 border-t border-white/5 flex justify-end">
          <button 
            onClick={onClose}
            className="px-8 py-3 bg-gold-500 text-black font-bold rounded-xl hover:bg-gold-400 transition-all shadow-lg"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};
